### ISSUE TITLE
Arrumar as frases.

### ISSUE THREAD

**Issue by cassioafs** [CassiaCaris/calculadora_ruby#1]
As frases estão invertidas:
```
Digite um numero?
1
Digite o Numero da Operacao escolhida?
1
Digite o segundo numero?
2
```
Acho que deveria ser:
```
Digite o Numero da Operacao escolhida?
1
Digite um numero?
1
Digite o segundo numero?
2
```
E alterar pergunta: 
"Digite o primeiro número", para "Digite o primeiro numero?"

**Comment by CassiaCaris** [comment]
Tratado.
Só não concordo a ordem.
No meu ponto de vista deve ser digitado o primeiro numero, a operação e na sequencia o segundo numero.
Conforme uma calculadora.
