### ISSUE TITLE
Permitir o cálculo com números negativos

### ISSUE THREAD

**Issue by cassioafs** [CassiaCaris/calculadora_ruby#4]
Permitir o cálculo com números negativos.
Por exemplo:
usuário escolhe soma e digita os valores
-10 e 2 
o resultado deve ser 8

usuário escolhe subtração e digita os valores
-10 e 2 
o resultado deve ser -12

usuário escolhe divisão e digita os valores
-3 e -3
o resultado deve ser 1 

usuário escolhe multiplicação e digita os valores
-1 e 2
o resultado deve ser -2

E também criar os cenários de teste.

**Comment by CassiaCaris** [comment]
Foi permitido o calculo com números negativos, e realizado alguns testes unitários para os mesmos.
Porém uma das condições solicitados era tratar os números negativos.

**Comment by cassioafs** [comment]
Acredito que o "tratar números negativos" era nesse sentido, de mostrar corretamente o sinal de negativo quando necessário.
