### ISSUE TITLE
Alterar nome da variável calculadora2.rb

### ISSUE THREAD

**Issue by cassioafs** [CassiaCaris/calculadora_ruby#6]
Alterar o nome da variável "a" presente no arquivo a = Calculadora.new

Um sugestão é sempre criar variáveis "auto explicativas" onde o nome dela representa exatamente o que ela significa, desse jeito fica mt mais fácil para quem for ler o código fonte e mais fácil para uma futura manutenção.

**Comment by CassiaCaris** [comment]
Nome da variável alterado.
